### ISSUE TITLE
#What does this mean when I used my own data for fine-tuning: 'RuntimeError: mat1 dim 1 must match mat2 dim 0'

### ISSUE THREAD

**Issue by yzhu-bnt** [TencentAILabHealthcare/scBERT#35]
What does this mean when I used my own data for fine-tuning: 'RuntimeError: mat1 dim 1 must match mat2 dim 0'?

I used scanpy Version: 1.9.3, Python 3.9.2. This should be ok, because I have run the tutorial smoothly, using Zheng68K.h5ad as fine-tuning data. 
I have also made sure there is an adata.obs['celltype'] column in my data. Any suggestion on how to go about with troubleshooting? thanks!

$ python -m torch.distributed.launch finetune.py --data_path "./data/ref9bgInteg.h5ad" --model_path "./data/panglao_pretrained.pth" > log0730_refine_bnt9BGinteg.txt
Traceback (most recent call last):
  File "/mnt/efs/yzhu/scbert/finetune.py", line 204, in <module>
    logits = model(data)
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/efs/yzhu/scbert/performer_pytorch/performer_pytorch.py", line 636, in forward
    x = self.to_out(x)
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/efs/yzhu/scbert/finetune.py", line 114, in forward
    x = self.fc1(x)
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0
Traceback (most recent call last):
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/yzhu/.conda/envs/scBERT2/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/yzhu/.conda/envs/scBERT2/bin/python', '-u', 'finetune.py', '--local_rank=0', '--data_path', './data/ref9bgInteg.h5ad', '--model_path', './data/panglao_pretrained.pth']' returned non-zero exit status 1.

**Comment by TencentAILabHealthcare** [comment]
Perhaps the data format is not exactly the same as the demo data Zheng68K. Please compare your own data and the demo data carefully, especially the gene number and gene list.
