### ISSUE TITLE
我想跑panglao_10000的数据集，但是有报错。

### ISSUE THREAD

**Issue by justSOZ** [TencentAILabHealthcare/scBERT#52]
(torch) server@lthpc-desktop:~/zjc_test_anytime-can-be-deleted $ python -m torch.distributed.run finetune.py
/home/server/anaconda3/envs/torch/lib/python3.8/site-packages/anndata/_core/anndata.py:1838: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Traceback (most recent call last):
  File "/home/server/anaconda3/envs/torch/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'celltype'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "finetune.py", line 131, in <module>
    label_dict, label = np.unique(np.array(data.obs['celltype']), return_inverse=True)  # Convert strings categorical to integrate categorical, and label_dict[label] can be restored
  File "/home/server/anaconda3/envs/torch/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/server/anaconda3/envs/torch/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'celltype'
[2024-04-17 16:58:34,877] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1109423) of binary: /home/server/anaconda3/envs/torch/bin/python
Traceback (most recent call last):
  File "/home/server/anaconda3/envs/torch/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/server/anaconda3/envs/torch/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/server/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/home/server/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/server/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/server/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/server/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/server/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-17_16:58:34
  host      : lthpc-desktop
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1109423)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

这是报错主题，然后，我正在看看是不是数据本身就有问题？？一个是有标签的数据，还是一个是没有标签的数据

**Comment by wangnuo-log** [comment]
你这个看起来像是合并在一起的数据没有celltype的这个列啊，所以没有办法进行微调的操作

**Comment by xin4396** [comment]
您好，请问您是否可以分享一下panglao_10000的dataset？（By the way, 是找author要的吗？）

**Comment by justSOZ** [comment]
数据集很大一个文件，我没得了，有预训练跑好的，你要的话我去找找

**Comment by xin4396** [comment]
是panglao10000.h5ad对吗？ 我过会给author发个邮件也行，感谢您 : )

**Comment by cpu-yun** [comment]
> 是panglao10000.h5ad对吗？ 我过会给author发个邮件也行，感谢您 : )

请问是preprocess.py里用到的嘛？
panglao = sc.read_h5ad('./data/panglao_10000.h5ad')

可以发我一份吗？谢谢！
